# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main1.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QHBoxLayout,
    QHeaderView, QLabel, QMainWindow, QMenu,
    QMenuBar, QPlainTextEdit, QPushButton, QSizePolicy,
    QSpacerItem, QSplitter, QStatusBar, QTabWidget,
    QTreeWidget, QTreeWidgetItem, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 450)
        self.import_sch_csv_m = QAction(MainWindow)
        self.import_sch_csv_m.setObjectName(u"import_sch_csv_m")
        self.import_sch_json_m = QAction(MainWindow)
        self.import_sch_json_m.setObjectName(u"import_sch_json_m")
        self.import_stb_csv_m = QAction(MainWindow)
        self.import_stb_csv_m.setObjectName(u"import_stb_csv_m")
        self.export_sch_csv_m = QAction(MainWindow)
        self.export_sch_csv_m.setObjectName(u"export_sch_csv_m")
        self.export_sch_json_m = QAction(MainWindow)
        self.export_sch_json_m.setObjectName(u"export_sch_json_m")
        self.open_save_folder_m = QAction(MainWindow)
        self.open_save_folder_m.setObjectName(u"open_save_folder_m")
        self.undo_m = QAction(MainWindow)
        self.undo_m.setObjectName(u"undo_m")
        self.redo_m = QAction(MainWindow)
        self.redo_m.setObjectName(u"redo_m")
        self.export_stb_csv_m = QAction(MainWindow)
        self.export_stb_csv_m.setObjectName(u"export_stb_csv_m")
        self.zoom_in_m = QAction(MainWindow)
        self.zoom_in_m.setObjectName(u"zoom_in_m")
        self.zoom_out_m = QAction(MainWindow)
        self.zoom_out_m.setObjectName(u"zoom_out_m")
        self.default_zoom_m = QAction(MainWindow)
        self.default_zoom_m.setObjectName(u"default_zoom_m")
        self.close_line_tab_m = QAction(MainWindow)
        self.close_line_tab_m.setObjectName(u"close_line_tab_m")
        self.close_all_tab_m = QAction(MainWindow)
        self.close_all_tab_m.setObjectName(u"close_all_tab_m")
        self.open_app_terminal_m = QAction(MainWindow)
        self.open_app_terminal_m.setObjectName(u"open_app_terminal_m")
        self.do_schedule_m = QAction(MainWindow)
        self.do_schedule_m.setObjectName(u"do_schedule_m")
        self.line_setting_m = QAction(MainWindow)
        self.line_setting_m.setObjectName(u"line_setting_m")
        self.frequency_setting_m = QAction(MainWindow)
        self.frequency_setting_m.setObjectName(u"frequency_setting_m")
        self.open_documantation_m = QAction(MainWindow)
        self.open_documantation_m.setObjectName(u"open_documantation_m")
        self.open_read_me_m = QAction(MainWindow)
        self.open_read_me_m.setObjectName(u"open_read_me_m")
        self.add_line_m = QAction(MainWindow)
        self.add_line_m.setObjectName(u"add_line_m")
        self.add_line_csv_m = QAction(MainWindow)
        self.add_line_csv_m.setObjectName(u"add_line_csv_m")
        self.delete_line_m = QAction(MainWindow)
        self.delete_line_m.setObjectName(u"delete_line_m")
        self.clone_line_m = QAction(MainWindow)
        self.clone_line_m.setObjectName(u"clone_line_m")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_3 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.line_color_changer = QLabel(self.centralwidget)
        self.line_color_changer.setObjectName(u"line_color_changer")
        self.line_color_changer.setMinimumSize(QSize(0, 3))
        self.line_color_changer.setMaximumSize(QSize(16777215, 5))

        self.verticalLayout_3.addWidget(self.line_color_changer)

        self.upper_frame = QFrame(self.centralwidget)
        self.upper_frame.setObjectName(u"upper_frame")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upper_frame.sizePolicy().hasHeightForWidth())
        self.upper_frame.setSizePolicy(sizePolicy)
        self.upper_frame.setMinimumSize(QSize(0, 30))
        self.upper_frame.setMaximumSize(QSize(16777215, 30))
        self.upper_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.upper_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.upper_frame)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.line_sl_frame = QFrame(self.upper_frame)
        self.line_sl_frame.setObjectName(u"line_sl_frame")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.line_sl_frame.sizePolicy().hasHeightForWidth())
        self.line_sl_frame.setSizePolicy(sizePolicy1)
        self.line_sl_frame.setMinimumSize(QSize(270, 30))
        self.line_sl_frame.setMaximumSize(QSize(270, 30))
        self.line_sl_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.line_sl_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.line_sl_frame)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(5, 3, 5, 3)
        self.line_Selection = QComboBox(self.line_sl_frame)
        self.line_Selection.setObjectName(u"line_Selection")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.line_Selection.sizePolicy().hasHeightForWidth())
        self.line_Selection.setSizePolicy(sizePolicy2)
        self.line_Selection.setMinimumSize(QSize(0, 22))
        self.line_Selection.setMaximumSize(QSize(16777215, 22))

        self.horizontalLayout_2.addWidget(self.line_Selection)

        self.load_1 = QPushButton(self.line_sl_frame)
        self.load_1.setObjectName(u"load_1")
        sizePolicy1.setHeightForWidth(self.load_1.sizePolicy().hasHeightForWidth())
        self.load_1.setSizePolicy(sizePolicy1)
        self.load_1.setMinimumSize(QSize(40, 0))
        self.load_1.setMaximumSize(QSize(40, 16777215))

        self.horizontalLayout_2.addWidget(self.load_1)


        self.horizontalLayout_3.addWidget(self.line_sl_frame)

        self.toolbox_frame1 = QFrame(self.upper_frame)
        self.toolbox_frame1.setObjectName(u"toolbox_frame1")
        self.toolbox_frame1.setFrameShape(QFrame.Shape.StyledPanel)
        self.toolbox_frame1.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout = QHBoxLayout(self.toolbox_frame1)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(5, 4, 5, 4)
        self.add_line_1 = QPushButton(self.toolbox_frame1)
        self.add_line_1.setObjectName(u"add_line_1")
        sizePolicy1.setHeightForWidth(self.add_line_1.sizePolicy().hasHeightForWidth())
        self.add_line_1.setSizePolicy(sizePolicy1)
        self.add_line_1.setMinimumSize(QSize(20, 20))
        self.add_line_1.setMaximumSize(QSize(20, 20))
        icon = QIcon()
        icon.addFile(u"assets/main_toolbar/add_route.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.add_line_1.setIcon(icon)

        self.horizontalLayout.addWidget(self.add_line_1)

        self.add_line_csv_1 = QPushButton(self.toolbox_frame1)
        self.add_line_csv_1.setObjectName(u"add_line_csv_1")
        sizePolicy1.setHeightForWidth(self.add_line_csv_1.sizePolicy().hasHeightForWidth())
        self.add_line_csv_1.setSizePolicy(sizePolicy1)
        self.add_line_csv_1.setMinimumSize(QSize(20, 20))
        self.add_line_csv_1.setMaximumSize(QSize(20, 20))
        icon1 = QIcon()
        icon1.addFile(u"assets/main_toolbar/add_route_csv.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.add_line_csv_1.setIcon(icon1)

        self.horizontalLayout.addWidget(self.add_line_csv_1)

        self.delete_line_1 = QPushButton(self.toolbox_frame1)
        self.delete_line_1.setObjectName(u"delete_line_1")
        sizePolicy1.setHeightForWidth(self.delete_line_1.sizePolicy().hasHeightForWidth())
        self.delete_line_1.setSizePolicy(sizePolicy1)
        self.delete_line_1.setMinimumSize(QSize(20, 20))
        self.delete_line_1.setMaximumSize(QSize(20, 20))
        icon2 = QIcon()
        icon2.addFile(u"assets/main_toolbar/delete_route.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.delete_line_1.setIcon(icon2)

        self.horizontalLayout.addWidget(self.delete_line_1)

        self.clone_line_1 = QPushButton(self.toolbox_frame1)
        self.clone_line_1.setObjectName(u"clone_line_1")
        sizePolicy1.setHeightForWidth(self.clone_line_1.sizePolicy().hasHeightForWidth())
        self.clone_line_1.setSizePolicy(sizePolicy1)
        self.clone_line_1.setMinimumSize(QSize(20, 20))
        self.clone_line_1.setMaximumSize(QSize(20, 20))
        icon3 = QIcon()
        icon3.addFile(u"assets/main_toolbar/clone_route.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.clone_line_1.setIcon(icon3)

        self.horizontalLayout.addWidget(self.clone_line_1)

        self.line1 = QFrame(self.toolbox_frame1)
        self.line1.setObjectName(u"line1")
        sizePolicy1.setHeightForWidth(self.line1.sizePolicy().hasHeightForWidth())
        self.line1.setSizePolicy(sizePolicy1)
        self.line1.setMinimumSize(QSize(5, 20))
        self.line1.setMaximumSize(QSize(5, 20))
        self.line1.setFrameShadow(QFrame.Shadow.Sunken)
        self.line1.setFrameShape(QFrame.Shape.VLine)

        self.horizontalLayout.addWidget(self.line1)

        self.do_schedule_1 = QPushButton(self.toolbox_frame1)
        self.do_schedule_1.setObjectName(u"do_schedule_1")
        sizePolicy1.setHeightForWidth(self.do_schedule_1.sizePolicy().hasHeightForWidth())
        self.do_schedule_1.setSizePolicy(sizePolicy1)
        self.do_schedule_1.setMinimumSize(QSize(20, 20))
        self.do_schedule_1.setMaximumSize(QSize(20, 20))
        icon4 = QIcon()
        icon4.addFile(u"assets/main_toolbar/do_schedule.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.do_schedule_1.setIcon(icon4)

        self.horizontalLayout.addWidget(self.do_schedule_1)

        self.stop_schedule_1 = QPushButton(self.toolbox_frame1)
        self.stop_schedule_1.setObjectName(u"stop_schedule_1")
        sizePolicy1.setHeightForWidth(self.stop_schedule_1.sizePolicy().hasHeightForWidth())
        self.stop_schedule_1.setSizePolicy(sizePolicy1)
        self.stop_schedule_1.setMinimumSize(QSize(20, 20))
        self.stop_schedule_1.setMaximumSize(QSize(20, 20))
        icon5 = QIcon()
        icon5.addFile(u"assets/main_toolbar/stop_schedule.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.stop_schedule_1.setIcon(icon5)

        self.horizontalLayout.addWidget(self.stop_schedule_1)

        self.line2 = QFrame(self.toolbox_frame1)
        self.line2.setObjectName(u"line2")
        sizePolicy1.setHeightForWidth(self.line2.sizePolicy().hasHeightForWidth())
        self.line2.setSizePolicy(sizePolicy1)
        self.line2.setMinimumSize(QSize(5, 20))
        self.line2.setMaximumSize(QSize(5, 20))
        self.line2.setFrameShadow(QFrame.Shadow.Sunken)
        self.line2.setFrameShape(QFrame.Shape.VLine)

        self.horizontalLayout.addWidget(self.line2)

        self.import_stb_csv_1 = QPushButton(self.toolbox_frame1)
        self.import_stb_csv_1.setObjectName(u"import_stb_csv_1")
        self.import_stb_csv_1.setMinimumSize(QSize(20, 20))
        self.import_stb_csv_1.setMaximumSize(QSize(20, 20))
        icon6 = QIcon()
        icon6.addFile(u"assets/main_toolbar/stb_csv_import.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.import_stb_csv_1.setIcon(icon6)

        self.horizontalLayout.addWidget(self.import_stb_csv_1)

        self.import_sch_csv_1 = QPushButton(self.toolbox_frame1)
        self.import_sch_csv_1.setObjectName(u"import_sch_csv_1")
        sizePolicy1.setHeightForWidth(self.import_sch_csv_1.sizePolicy().hasHeightForWidth())
        self.import_sch_csv_1.setSizePolicy(sizePolicy1)
        self.import_sch_csv_1.setMinimumSize(QSize(20, 20))
        self.import_sch_csv_1.setMaximumSize(QSize(20, 20))

        self.horizontalLayout.addWidget(self.import_sch_csv_1)

        self.export_sch_csv_1 = QPushButton(self.toolbox_frame1)
        self.export_sch_csv_1.setObjectName(u"export_sch_csv_1")
        sizePolicy1.setHeightForWidth(self.export_sch_csv_1.sizePolicy().hasHeightForWidth())
        self.export_sch_csv_1.setSizePolicy(sizePolicy1)
        self.export_sch_csv_1.setMinimumSize(QSize(20, 20))
        self.export_sch_csv_1.setMaximumSize(QSize(20, 20))

        self.horizontalLayout.addWidget(self.export_sch_csv_1)

        self.export_sch_json_1 = QPushButton(self.toolbox_frame1)
        self.export_sch_json_1.setObjectName(u"export_sch_json_1")
        sizePolicy1.setHeightForWidth(self.export_sch_json_1.sizePolicy().hasHeightForWidth())
        self.export_sch_json_1.setSizePolicy(sizePolicy1)
        self.export_sch_json_1.setMinimumSize(QSize(20, 20))
        self.export_sch_json_1.setMaximumSize(QSize(20, 20))

        self.horizontalLayout.addWidget(self.export_sch_json_1)

        self.line3 = QFrame(self.toolbox_frame1)
        self.line3.setObjectName(u"line3")
        sizePolicy1.setHeightForWidth(self.line3.sizePolicy().hasHeightForWidth())
        self.line3.setSizePolicy(sizePolicy1)
        self.line3.setMinimumSize(QSize(5, 20))
        self.line3.setMaximumSize(QSize(5, 20))
        self.line3.setFrameShadow(QFrame.Shadow.Sunken)
        self.line3.setFrameShape(QFrame.Shape.VLine)

        self.horizontalLayout.addWidget(self.line3)

        self.zoom_in_1 = QPushButton(self.toolbox_frame1)
        self.zoom_in_1.setObjectName(u"zoom_in_1")
        sizePolicy1.setHeightForWidth(self.zoom_in_1.sizePolicy().hasHeightForWidth())
        self.zoom_in_1.setSizePolicy(sizePolicy1)
        self.zoom_in_1.setMinimumSize(QSize(20, 20))
        self.zoom_in_1.setMaximumSize(QSize(20, 20))

        self.horizontalLayout.addWidget(self.zoom_in_1)

        self.zoom_out_1 = QPushButton(self.toolbox_frame1)
        self.zoom_out_1.setObjectName(u"zoom_out_1")
        sizePolicy1.setHeightForWidth(self.zoom_out_1.sizePolicy().hasHeightForWidth())
        self.zoom_out_1.setSizePolicy(sizePolicy1)
        self.zoom_out_1.setMinimumSize(QSize(20, 20))
        self.zoom_out_1.setMaximumSize(QSize(20, 20))

        self.horizontalLayout.addWidget(self.zoom_out_1)

        self.default_zoom_1 = QPushButton(self.toolbox_frame1)
        self.default_zoom_1.setObjectName(u"default_zoom_1")
        sizePolicy1.setHeightForWidth(self.default_zoom_1.sizePolicy().hasHeightForWidth())
        self.default_zoom_1.setSizePolicy(sizePolicy1)
        self.default_zoom_1.setMinimumSize(QSize(20, 20))
        self.default_zoom_1.setMaximumSize(QSize(20, 20))

        self.horizontalLayout.addWidget(self.default_zoom_1)

        self.line3_2 = QFrame(self.toolbox_frame1)
        self.line3_2.setObjectName(u"line3_2")
        sizePolicy1.setHeightForWidth(self.line3_2.sizePolicy().hasHeightForWidth())
        self.line3_2.setSizePolicy(sizePolicy1)
        self.line3_2.setMinimumSize(QSize(5, 20))
        self.line3_2.setMaximumSize(QSize(5, 20))
        self.line3_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.line3_2.setFrameShape(QFrame.Shape.VLine)

        self.horizontalLayout.addWidget(self.line3_2)

        self.line_setting_1 = QPushButton(self.toolbox_frame1)
        self.line_setting_1.setObjectName(u"line_setting_1")
        sizePolicy1.setHeightForWidth(self.line_setting_1.sizePolicy().hasHeightForWidth())
        self.line_setting_1.setSizePolicy(sizePolicy1)
        self.line_setting_1.setMinimumSize(QSize(20, 20))
        self.line_setting_1.setMaximumSize(QSize(20, 20))
        icon7 = QIcon()
        icon7.addFile(u"assets/main_toolbar/line_setting.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.line_setting_1.setIcon(icon7)

        self.horizontalLayout.addWidget(self.line_setting_1)

        self.horizontalSpacer_1 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_1)

        self.app_setting_1 = QPushButton(self.toolbox_frame1)
        self.app_setting_1.setObjectName(u"app_setting_1")
        sizePolicy1.setHeightForWidth(self.app_setting_1.sizePolicy().hasHeightForWidth())
        self.app_setting_1.setSizePolicy(sizePolicy1)
        self.app_setting_1.setMinimumSize(QSize(20, 20))
        self.app_setting_1.setMaximumSize(QSize(20, 20))
        self.app_setting_1.setLayoutDirection(Qt.LayoutDirection.LeftToRight)

        self.horizontalLayout.addWidget(self.app_setting_1)

        self.open_app_terminal_1 = QPushButton(self.toolbox_frame1)
        self.open_app_terminal_1.setObjectName(u"open_app_terminal_1")
        sizePolicy1.setHeightForWidth(self.open_app_terminal_1.sizePolicy().hasHeightForWidth())
        self.open_app_terminal_1.setSizePolicy(sizePolicy1)
        self.open_app_terminal_1.setMinimumSize(QSize(20, 20))
        self.open_app_terminal_1.setMaximumSize(QSize(20, 20))
        self.open_app_terminal_1.setLayoutDirection(Qt.LayoutDirection.RightToLeft)

        self.horizontalLayout.addWidget(self.open_app_terminal_1)


        self.horizontalLayout_3.addWidget(self.toolbox_frame1)


        self.verticalLayout_3.addWidget(self.upper_frame)

        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setChildrenCollapsible(False)
        self.left_box = QFrame(self.splitter)
        self.left_box.setObjectName(u"left_box")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.left_box.sizePolicy().hasHeightForWidth())
        self.left_box.setSizePolicy(sizePolicy3)
        self.left_box.setMinimumSize(QSize(240, 0))
        self.left_box.setMaximumSize(QSize(640, 16777215))
        self.left_box.setBaseSize(QSize(160, 0))
        self.left_box.setFrameShape(QFrame.Shape.StyledPanel)
        self.left_box.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.left_box)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.splitter_2 = QSplitter(self.left_box)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setOrientation(Qt.Orientation.Vertical)
        self.splitter_2.setChildrenCollapsible(False)
        self.guide_treelist = QTreeWidget(self.splitter_2)
        __qtreewidgetitem = QTreeWidgetItem(self.guide_treelist)
        QTreeWidgetItem(__qtreewidgetitem)
        QTreeWidgetItem(__qtreewidgetitem)
        QTreeWidgetItem(__qtreewidgetitem)
        QTreeWidgetItem(__qtreewidgetitem)
        __qtreewidgetitem1 = QTreeWidgetItem(self.guide_treelist)
        QTreeWidgetItem(__qtreewidgetitem1)
        QTreeWidgetItem(__qtreewidgetitem1)
        QTreeWidgetItem(__qtreewidgetitem1)
        QTreeWidgetItem(__qtreewidgetitem1)
        __qtreewidgetitem2 = QTreeWidgetItem(self.guide_treelist)
        QTreeWidgetItem(__qtreewidgetitem2)
        QTreeWidgetItem(__qtreewidgetitem2)
        QTreeWidgetItem(__qtreewidgetitem2)
        __qtreewidgetitem3 = QTreeWidgetItem(self.guide_treelist)
        QTreeWidgetItem(__qtreewidgetitem3)
        __qtreewidgetitem4 = QTreeWidgetItem(self.guide_treelist)
        QTreeWidgetItem(__qtreewidgetitem4)
        QTreeWidgetItem(__qtreewidgetitem4)
        QTreeWidgetItem(__qtreewidgetitem4)
        QTreeWidgetItem(__qtreewidgetitem4)
        __qtreewidgetitem5 = QTreeWidgetItem(self.guide_treelist)
        QTreeWidgetItem(__qtreewidgetitem5)
        QTreeWidgetItem(__qtreewidgetitem5)
        QTreeWidgetItem(__qtreewidgetitem5)
        QTreeWidgetItem(__qtreewidgetitem5)
        self.guide_treelist.setObjectName(u"guide_treelist")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(7)
        sizePolicy4.setHeightForWidth(self.guide_treelist.sizePolicy().hasHeightForWidth())
        self.guide_treelist.setSizePolicy(sizePolicy4)
        self.guide_treelist.setFrameShape(QFrame.Shape.NoFrame)
        self.guide_treelist.setFrameShadow(QFrame.Shadow.Plain)
        self.guide_treelist.setLineWidth(1)
        self.guide_treelist.setAllColumnsShowFocus(False)
        self.guide_treelist.setHeaderHidden(True)
        self.splitter_2.addWidget(self.guide_treelist)
        self.output_frame = QFrame(self.splitter_2)
        self.output_frame.setObjectName(u"output_frame")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(2)
        sizePolicy5.setHeightForWidth(self.output_frame.sizePolicy().hasHeightForWidth())
        self.output_frame.setSizePolicy(sizePolicy5)
        self.output_frame.setMinimumSize(QSize(0, 60))
        self.output_frame.setMaximumSize(QSize(16777215, 360))
        self.output_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.output_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout = QVBoxLayout(self.output_frame)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(5, 5, 5, 0)
        self.sys_output_label_1 = QLabel(self.output_frame)
        self.sys_output_label_1.setObjectName(u"sys_output_label_1")
        sizePolicy.setHeightForWidth(self.sys_output_label_1.sizePolicy().hasHeightForWidth())
        self.sys_output_label_1.setSizePolicy(sizePolicy)
        self.sys_output_label_1.setMinimumSize(QSize(0, 16))
        self.sys_output_label_1.setMaximumSize(QSize(16777215, 16))
        self.sys_output_label_1.setFrameShadow(QFrame.Shadow.Sunken)
        self.sys_output_label_1.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.verticalLayout.addWidget(self.sys_output_label_1)

        self.plainTextEdit = QPlainTextEdit(self.output_frame)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setFrameShape(QFrame.Shape.NoFrame)
        self.plainTextEdit.setReadOnly(True)

        self.verticalLayout.addWidget(self.plainTextEdit)

        self.splitter_2.addWidget(self.output_frame)

        self.verticalLayout_2.addWidget(self.splitter_2)

        self.splitter.addWidget(self.left_box)
        self.main_output = QTabWidget(self.splitter)
        self.main_output.setObjectName(u"main_output")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy6.setHorizontalStretch(2)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.main_output.sizePolicy().hasHeightForWidth())
        self.main_output.setSizePolicy(sizePolicy6)
        self.main_output.setDocumentMode(True)
        self.stb = QWidget()
        self.stb.setObjectName(u"stb")
        self.main_output.addTab(self.stb, "")
        self.train_level = QWidget()
        self.train_level.setObjectName(u"train_level")
        self.main_output.addTab(self.train_level, "")
        self.splitter.addWidget(self.main_output)

        self.verticalLayout_3.addWidget(self.splitter)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        self.files_folder_m = QMenu(self.menubar)
        self.files_folder_m.setObjectName(u"files_folder_m")
        self.edit_folder_m = QMenu(self.menubar)
        self.edit_folder_m.setObjectName(u"edit_folder_m")
        self.view_folder_m = QMenu(self.menubar)
        self.view_folder_m.setObjectName(u"view_folder_m")
        self.action_folder_m = QMenu(self.menubar)
        self.action_folder_m.setObjectName(u"action_folder_m")
        self.line_setting_folder_m = QMenu(self.menubar)
        self.line_setting_folder_m.setObjectName(u"line_setting_folder_m")
        self.about_folder_m = QMenu(self.menubar)
        self.about_folder_m.setObjectName(u"about_folder_m")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setStyleSheet(u"QStatusBar {\n"
"    border-top: 1px solid #CCCCCC;  /*\u6dfa\u7070\u8272\u7684\u4e0a\u908a\u6846 */\n"
"    background-color: #F8F9FA;      /* \u6975\u6dfa\u7684\u7070\u8272\u80cc\u666f */\n"
"}")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.files_folder_m.menuAction())
        self.menubar.addAction(self.edit_folder_m.menuAction())
        self.menubar.addAction(self.view_folder_m.menuAction())
        self.menubar.addAction(self.action_folder_m.menuAction())
        self.menubar.addAction(self.line_setting_folder_m.menuAction())
        self.menubar.addAction(self.about_folder_m.menuAction())
        self.files_folder_m.addAction(self.import_sch_csv_m)
        self.files_folder_m.addAction(self.import_sch_json_m)
        self.files_folder_m.addAction(self.import_stb_csv_m)
        self.files_folder_m.addSeparator()
        self.files_folder_m.addAction(self.export_sch_csv_m)
        self.files_folder_m.addAction(self.export_sch_json_m)
        self.files_folder_m.addAction(self.export_stb_csv_m)
        self.files_folder_m.addSeparator()
        self.files_folder_m.addAction(self.open_save_folder_m)
        self.edit_folder_m.addAction(self.undo_m)
        self.edit_folder_m.addAction(self.redo_m)
        self.edit_folder_m.addSeparator()
        self.edit_folder_m.addAction(self.add_line_m)
        self.edit_folder_m.addAction(self.add_line_csv_m)
        self.edit_folder_m.addAction(self.delete_line_m)
        self.edit_folder_m.addAction(self.clone_line_m)
        self.view_folder_m.addAction(self.zoom_in_m)
        self.view_folder_m.addAction(self.zoom_out_m)
        self.view_folder_m.addAction(self.default_zoom_m)
        self.view_folder_m.addSeparator()
        self.view_folder_m.addAction(self.close_line_tab_m)
        self.view_folder_m.addAction(self.close_all_tab_m)
        self.view_folder_m.addSeparator()
        self.view_folder_m.addAction(self.open_app_terminal_m)
        self.action_folder_m.addAction(self.do_schedule_m)
        self.line_setting_folder_m.addAction(self.line_setting_m)
        self.line_setting_folder_m.addAction(self.frequency_setting_m)
        self.about_folder_m.addAction(self.open_documantation_m)
        self.about_folder_m.addAction(self.open_read_me_m)

        self.retranslateUi(MainWindow)

        self.main_output.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.import_sch_csv_m.setText(QCoreApplication.translate("MainWindow", u"\u532f\u5165\u6642\u523b\u8868(.csv)", None))
        self.import_sch_json_m.setText(QCoreApplication.translate("MainWindow", u"\u532f\u5165\u6642\u523b\u8868(.json)", None))
        self.import_stb_csv_m.setText(QCoreApplication.translate("MainWindow", u"\u532f\u5165\u57fa\u6e96\u904b\u8f38\u6642\u523b\u8868(.csv)", None))
        self.export_sch_csv_m.setText(QCoreApplication.translate("MainWindow", u"\u532f\u51fa\u6642\u523b\u8868(.csv)", None))
        self.export_sch_json_m.setText(QCoreApplication.translate("MainWindow", u"\u532f\u51fa\u6642\u523b\u8868(.json)", None))
        self.open_save_folder_m.setText(QCoreApplication.translate("MainWindow", u"\u958b\u555f\u5b58\u6a94\u4f4d\u7f6e", None))
        self.undo_m.setText(QCoreApplication.translate("MainWindow", u"\u5fa9\u539f", None))
#if QT_CONFIG(tooltip)
        self.undo_m.setToolTip(QCoreApplication.translate("MainWindow", u"\u5fa9\u539f (\u5feb\u6377\u9375ctrl+z)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.undo_m.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.redo_m.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u505a", None))
#if QT_CONFIG(tooltip)
        self.redo_m.setToolTip(QCoreApplication.translate("MainWindow", u"\u91cd\u505a (\u5feb\u6377\u9375:ctrl+y)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.redo_m.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.export_stb_csv_m.setText(QCoreApplication.translate("MainWindow", u"\u532f\u51fa\u57fa\u6e96\u904b\u8f38\u6642\u523b\u8868(.csv)", None))
        self.zoom_in_m.setText(QCoreApplication.translate("MainWindow", u"\u653e\u5927\u8996\u5716", None))
        self.zoom_out_m.setText(QCoreApplication.translate("MainWindow", u"\u7e2e\u5c0f\u8996\u5716", None))
        self.default_zoom_m.setText(QCoreApplication.translate("MainWindow", u"\u56de\u5fa9\u9810\u8a2d\u8996\u5716\u5927\u5c0f", None))
        self.close_line_tab_m.setText(QCoreApplication.translate("MainWindow", u"\u95dc\u9589\u76ee\u524d\u8def\u7dda\u6240\u6709\u8996\u5716", None))
        self.close_all_tab_m.setText(QCoreApplication.translate("MainWindow", u"\u95dc\u9589\u6240\u6709\u8996\u5716", None))
        self.open_app_terminal_m.setText(QCoreApplication.translate("MainWindow", u"\u958b\u555f\u7cfb\u7d71\u63a7\u5236\u53f0", None))
        self.do_schedule_m.setText(QCoreApplication.translate("MainWindow", u"\u958b\u59cb\u6a21\u64ec\u6392\u73ed", None))
#if QT_CONFIG(tooltip)
        self.do_schedule_m.setToolTip(QCoreApplication.translate("MainWindow", u"\u958b\u59cb\u6a21\u64ec\u6392\u73ed (\u5feb\u6377\u9375:f5)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.do_schedule_m.setShortcut(QCoreApplication.translate("MainWindow", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.line_setting_m.setText(QCoreApplication.translate("MainWindow", u"\u8def\u7dda\u8a2d\u5b9a", None))
        self.frequency_setting_m.setText(QCoreApplication.translate("MainWindow", u"\u73ed\u6b21\u5bc6\u5ea6\u8a2d\u5b9a", None))
        self.open_documantation_m.setText(QCoreApplication.translate("MainWindow", u"\u64cd\u4f5c\u624b\u518a", None))
        self.open_read_me_m.setText(QCoreApplication.translate("MainWindow", u"\u95dc\u65bc", None))
        self.add_line_m.setText(QCoreApplication.translate("MainWindow", u"\u5275\u5efa\u65b0\u8def\u7dda", None))
        self.add_line_csv_m.setText(QCoreApplication.translate("MainWindow", u"\u5275\u5efa\u65b0\u8def\u7dda(\u532f\u5165.csv\u57fa\u6e96\u904b\u8f38\u6642\u523b\u8868)", None))
        self.delete_line_m.setText(QCoreApplication.translate("MainWindow", u"\u522a\u9664\u8def\u7dda", None))
        self.clone_line_m.setText(QCoreApplication.translate("MainWindow", u"\u8907\u88fd\u8def\u7dda", None))
        self.line_color_changer.setText("")
        self.line_Selection.setCurrentText("")
        self.line_Selection.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u9078\u64c7\u8def\u7dda", None))
        self.load_1.setText(QCoreApplication.translate("MainWindow", u"\u8f09\u5165", None))
#if QT_CONFIG(tooltip)
        self.add_line_1.setToolTip(QCoreApplication.translate("MainWindow", u"\u5275\u5efa\u65b0\u8def\u7dda", None))
#endif // QT_CONFIG(tooltip)
        self.add_line_1.setText("")
#if QT_CONFIG(tooltip)
        self.add_line_csv_1.setToolTip(QCoreApplication.translate("MainWindow", u"\u5275\u5efa\u65b0\u8def\u7dda(\u532f\u5165.csv\u57fa\u6e96\u904b\u8f38\u6642\u523b\u8868)", None))
#endif // QT_CONFIG(tooltip)
        self.add_line_csv_1.setText("")
#if QT_CONFIG(tooltip)
        self.delete_line_1.setToolTip(QCoreApplication.translate("MainWindow", u"\u522a\u9664\u8def\u7dda", None))
#endif // QT_CONFIG(tooltip)
        self.delete_line_1.setText("")
#if QT_CONFIG(tooltip)
        self.clone_line_1.setToolTip(QCoreApplication.translate("MainWindow", u"\u8907\u88fd\u8def\u7dda", None))
#endif // QT_CONFIG(tooltip)
        self.clone_line_1.setText("")
#if QT_CONFIG(tooltip)
        self.do_schedule_1.setToolTip(QCoreApplication.translate("MainWindow", u"\u958b\u59cb\u6a21\u64ec\u6392\u73ed", None))
#endif // QT_CONFIG(tooltip)
        self.do_schedule_1.setText("")
#if QT_CONFIG(tooltip)
        self.stop_schedule_1.setToolTip(QCoreApplication.translate("MainWindow", u"\u505c\u6b62\u6a21\u64ec\u6392\u73ed", None))
#endif // QT_CONFIG(tooltip)
        self.stop_schedule_1.setText("")
#if QT_CONFIG(tooltip)
        self.import_stb_csv_1.setToolTip(QCoreApplication.translate("MainWindow", u"\u532f\u5165\u57fa\u6e96\u904b\u8f38\u6642\u523b\u8868(.csv)", None))
#endif // QT_CONFIG(tooltip)
        self.import_stb_csv_1.setText("")
#if QT_CONFIG(tooltip)
        self.import_sch_csv_1.setToolTip(QCoreApplication.translate("MainWindow", u"\u532f\u5165\u6642\u523b\u8868(.csv)", None))
#endif // QT_CONFIG(tooltip)
        self.import_sch_csv_1.setText("")
#if QT_CONFIG(tooltip)
        self.export_sch_csv_1.setToolTip(QCoreApplication.translate("MainWindow", u"\u8f38\u51fa\u7d50\u679c\u6392\u73ed(.csv)", None))
#endif // QT_CONFIG(tooltip)
        self.export_sch_csv_1.setText("")
#if QT_CONFIG(tooltip)
        self.export_sch_json_1.setToolTip(QCoreApplication.translate("MainWindow", u"\u8f38\u51fa\u7d50\u679c\u6392\u73ed(.json)", None))
#endif // QT_CONFIG(tooltip)
        self.export_sch_json_1.setText("")
#if QT_CONFIG(tooltip)
        self.zoom_in_1.setToolTip(QCoreApplication.translate("MainWindow", u"\u653e\u5927", None))
#endif // QT_CONFIG(tooltip)
        self.zoom_in_1.setText("")
#if QT_CONFIG(tooltip)
        self.zoom_out_1.setToolTip(QCoreApplication.translate("MainWindow", u"\u7e2e\u5c0f", None))
#endif // QT_CONFIG(tooltip)
        self.zoom_out_1.setText("")
#if QT_CONFIG(tooltip)
        self.default_zoom_1.setToolTip(QCoreApplication.translate("MainWindow", u"\u9810\u8a2d\u5927\u5c0f\u02c7", None))
#endif // QT_CONFIG(tooltip)
        self.default_zoom_1.setText("")
#if QT_CONFIG(tooltip)
        self.line_setting_1.setToolTip(QCoreApplication.translate("MainWindow", u"\u8def\u7dda\u8a2d\u5b9a", None))
#endif // QT_CONFIG(tooltip)
        self.line_setting_1.setText("")
#if QT_CONFIG(tooltip)
        self.app_setting_1.setToolTip(QCoreApplication.translate("MainWindow", u"\u7cfb\u7d71\u8a2d\u5b9a", None))
#endif // QT_CONFIG(tooltip)
        self.app_setting_1.setText("")
#if QT_CONFIG(tooltip)
        self.open_app_terminal_1.setToolTip(QCoreApplication.translate("MainWindow", u"\u958b\u555f\u7cfb\u7d71\u7ba1\u7406\u53f0", None))
#endif // QT_CONFIG(tooltip)
        self.open_app_terminal_1.setText("")
        ___qtreewidgetitem = self.guide_treelist.headerItem()
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("MainWindow", u"\u5c0e\u89bd\u5217", None));

        __sortingEnabled = self.guide_treelist.isSortingEnabled()
        self.guide_treelist.setSortingEnabled(False)
        ___qtreewidgetitem1 = self.guide_treelist.topLevelItem(0)
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("MainWindow", u"\u74b0\u5883\u8a2d\u5b9a", None));
        ___qtreewidgetitem2 = ___qtreewidgetitem1.child(0)
        ___qtreewidgetitem2.setText(0, QCoreApplication.translate("MainWindow", u"\u8eca\u7ad9\u8207\u8eca\u8f1b\u8a2d\u65bd\u8a2d\u7f6e\u8868", None));
        ___qtreewidgetitem3 = ___qtreewidgetitem1.child(1)
        ___qtreewidgetitem3.setText(0, QCoreApplication.translate("MainWindow", u"\u8eca\u7ad9\u8207\u8eca\u8f1b\u8a2d\u65bd\u5716", None));
        ___qtreewidgetitem4 = ___qtreewidgetitem1.child(2)
        ___qtreewidgetitem4.setText(0, QCoreApplication.translate("MainWindow", u"\u8def\u7dda\u7e3d\u5716", None));
        ___qtreewidgetitem5 = ___qtreewidgetitem1.child(3)
        ___qtreewidgetitem5.setText(0, QCoreApplication.translate("MainWindow", u"\u76f4\u901a\u8def\u7dda\u8a2d\u7f6e\u8868", None));
        ___qtreewidgetitem6 = self.guide_treelist.topLevelItem(1)
        ___qtreewidgetitem6.setText(0, QCoreApplication.translate("MainWindow", u"\u8def\u7dda\u57fa\u672c\u8a2d\u5b9a", None));
        ___qtreewidgetitem7 = ___qtreewidgetitem6.child(0)
        ___qtreewidgetitem7.setText(0, QCoreApplication.translate("MainWindow", u"\u57fa\u672c\u904b\u8f38\u6642\u523b\u8868(\u4e0a\u884c)", None));
        ___qtreewidgetitem8 = ___qtreewidgetitem6.child(1)
        ___qtreewidgetitem8.setText(0, QCoreApplication.translate("MainWindow", u"\u57fa\u672c\u904b\u8f38\u6642\u523b\u8868(\u4e0b\u884c)", None));
        ___qtreewidgetitem9 = ___qtreewidgetitem6.child(2)
        ___qtreewidgetitem9.setText(0, QCoreApplication.translate("MainWindow", u"\u5217\u8eca\u7b49\u7d1a\u8868", None));
        ___qtreewidgetitem10 = ___qtreewidgetitem6.child(3)
        ___qtreewidgetitem10.setText(0, QCoreApplication.translate("MainWindow", u"\u767c\u8eca\u983b\u7387\u8a2d\u5b9a\u8868", None));
        ___qtreewidgetitem11 = self.guide_treelist.topLevelItem(2)
        ___qtreewidgetitem11.setText(0, QCoreApplication.translate("MainWindow", u"\u8def\u7dda\u57fa\u672c\u8cc7\u8a0a", None));
        ___qtreewidgetitem12 = ___qtreewidgetitem11.child(0)
        ___qtreewidgetitem12.setText(0, QCoreApplication.translate("MainWindow", u"\u8def\u7dda\u5716", None));
        ___qtreewidgetitem13 = ___qtreewidgetitem11.child(1)
        ___qtreewidgetitem13.setText(0, QCoreApplication.translate("MainWindow", u"\u8eca\u7ad9\u914d\u7f6e\u5716", None));
        ___qtreewidgetitem14 = ___qtreewidgetitem11.child(2)
        ___qtreewidgetitem14.setText(0, QCoreApplication.translate("MainWindow", u"\u8eca\u8f1b\u52d5\u614b\u5716", None));
        ___qtreewidgetitem15 = self.guide_treelist.topLevelItem(3)
        ___qtreewidgetitem15.setText(0, QCoreApplication.translate("MainWindow", u"\u8def\u7dda\u8eca\u8f1b\u8a2d\u5b9a", None));
        ___qtreewidgetitem16 = ___qtreewidgetitem15.child(0)
        ___qtreewidgetitem16.setText(0, QCoreApplication.translate("MainWindow", u"\u8eca\u8f1b\u8cc7\u8a0a\u8868", None));
        ___qtreewidgetitem17 = self.guide_treelist.topLevelItem(4)
        ___qtreewidgetitem17.setText(0, QCoreApplication.translate("MainWindow", u"\u5e73\u65e5\u6642\u523b\u8868", None));
        ___qtreewidgetitem18 = ___qtreewidgetitem17.child(0)
        ___qtreewidgetitem18.setText(0, QCoreApplication.translate("MainWindow", u"\u4e0a\u884c\u73ed\u6b21\u6642\u523b\u8868", None));
        ___qtreewidgetitem19 = ___qtreewidgetitem17.child(1)
        ___qtreewidgetitem19.setText(0, QCoreApplication.translate("MainWindow", u"\u4e0b\u884c\u73ed\u6b21\u6642\u523b\u8868", None));
        ___qtreewidgetitem20 = ___qtreewidgetitem17.child(2)
        ___qtreewidgetitem20.setText(0, QCoreApplication.translate("MainWindow", u"\u8eca\u7ad9\u6642\u523b\u8868", None));
        ___qtreewidgetitem21 = ___qtreewidgetitem17.child(3)
        ___qtreewidgetitem21.setText(0, QCoreApplication.translate("MainWindow", u"\u8eca\u8f1b\u904b\u7528\u8868", None));
        ___qtreewidgetitem22 = self.guide_treelist.topLevelItem(5)
        ___qtreewidgetitem22.setText(0, QCoreApplication.translate("MainWindow", u"\u5047\u65e5\u6642\u523b\u8868", None));
        ___qtreewidgetitem23 = ___qtreewidgetitem22.child(0)
        ___qtreewidgetitem23.setText(0, QCoreApplication.translate("MainWindow", u"\u4e0a\u884c\u73ed\u6b21\u6642\u523b\u8868", None));
        ___qtreewidgetitem24 = ___qtreewidgetitem22.child(1)
        ___qtreewidgetitem24.setText(0, QCoreApplication.translate("MainWindow", u"\u4e0b\u884c\u73ed\u6b21\u6642\u523b\u8868", None));
        ___qtreewidgetitem25 = ___qtreewidgetitem22.child(2)
        ___qtreewidgetitem25.setText(0, QCoreApplication.translate("MainWindow", u"\u8eca\u7ad9\u6642\u523b\u8868", None));
        ___qtreewidgetitem26 = ___qtreewidgetitem22.child(3)
        ___qtreewidgetitem26.setText(0, QCoreApplication.translate("MainWindow", u"\u8eca\u8f1b\u904b\u7528\u8868", None));
        self.guide_treelist.setSortingEnabled(__sortingEnabled)

        self.sys_output_label_1.setText(QCoreApplication.translate("MainWindow", u"\u7cfb\u7d71\u8a0a\u606f", None))
        self.main_output.setTabText(self.main_output.indexOf(self.stb), QCoreApplication.translate("MainWindow", u"Tab 1", None))
        self.main_output.setTabText(self.main_output.indexOf(self.train_level), QCoreApplication.translate("MainWindow", u"Tab 2", None))
        self.files_folder_m.setTitle(QCoreApplication.translate("MainWindow", u"\u6a94\u6848", None))
        self.edit_folder_m.setTitle(QCoreApplication.translate("MainWindow", u"\u7de8\u8f2f", None))
        self.view_folder_m.setTitle(QCoreApplication.translate("MainWindow", u"\u6aa2\u8996", None))
        self.action_folder_m.setTitle(QCoreApplication.translate("MainWindow", u"\u57f7\u884c", None))
        self.line_setting_folder_m.setTitle(QCoreApplication.translate("MainWindow", u"\u8def\u7dda\u8a2d\u5b9a", None))
        self.about_folder_m.setTitle(QCoreApplication.translate("MainWindow", u"\u95dc\u65bc\u7cfb\u7d71", None))
    # retranslateUi

